#!/bin/bash
#PBS -q beda
#PBS -A C3SE2015-1-28
#PBS -l nodes=1:ppn=8
#PBS -l walltime=05:00:00

cd $PBS_O_WORKDIR
module purge
module load COURSES/TIF035
export GPAW_SETUP_PATH=$PBS_O_WORKDIR:$GPAW_SETUP_PATH
python ./mainFor.py 
